### ISSUE TITLE
Advanced HTML&CSS: Custom Properties

### ISSUE THREAD

**Issue by codingbootcampseu** [EeveeInGaa/bootcamp-schedule#39]
- [x] Replace all your colors with custom properties

**Hints**

```css
body {
  --main-color: red;
}

h1 {
  border: 2px solid var(--main-color);
}
```

**Bonus**

Add a media query that changes the colors of your cv based on the color scheme preferences of the visitor.

```css
body {
  --page-background-color: white;
  --page-text-color: black;
}

@media screen and (prefers-color-scheme: dark) {
  body {
    --page-background-color: black;
    --page-text-color: white;
  }
}
```

**Example Solution and Comparison**

- [Example solution](https://codesandbox.io/s/github/coding-bootcamps-eu/lexample-cv/blob/custom-properties/) for this task
- [Comparison to previous task](https://github.com/coding-bootcamps-eu/lexample-cv/compare/background...custom-properties)
